### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by pegahcarter** [best-practicers/reviews#32]

**Comment by rihp** [comment]
:wave:

Here is the project repo https://github.com/weiWard

**Comment by rihp** [comment]
Testing frameworks:
 - brownie for python
 - hardhat for javascript

TODOs:


- [ ] Look into big projects and how they have done the tests before.
- [ ] Make sure all functions in the contracts have at least 2 tests for each function

**Comment by rihp** [comment]
recommended flow: Lint-> Compile -> Tests

**Comment by rihp** [comment]
Hey @carlfarterson  

Looking through the code with @RCantu92, we tried to run the tests by following the readme, but the types from the `ethers-v5` module seems to be missing or with a wrong path.

here's the error log:
![image](https://user-images.githubusercontent.com/12145726/120022266-76211a00-bfec-11eb-8faa-a6e9f67967d2.png)

and this is the line which originates the error:  
- https://github.com/weiWard/weiward-contracts/blob/39ad0b497482701134c99449ab2bceb66610d747/test/deploy/ETHtx.test.ts#L12)

One potential solution we're thinking off is changing this route or importing the types manually, in order to try to run the tests. Should we try modifying the code ourselves locally?

**Comment by kjr217** [comment]
> Hey @carlfarterson
> 
> Looking through the code with @RCantu92, we tried to run the tests by following the readme, but the types from the `ethers-v5` module seems to be missing or with a wrong path.
> 
> here's the error log:
> ![image](https://user-images.githubusercontent.com/12145726/120022266-76211a00-bfec-11eb-8faa-a6e9f67967d2.png)
> 
> and this is the line which originates the error:
> 
> * https://github.com/weiWard/weiward-contracts/blob/39ad0b497482701134c99449ab2bceb66610d747/test/deploy/ETHtx.test.ts#L12)
> 
> One potential solution we're thinking off is changing this route or importing the types manually, in order to try to run the tests. Should we try modifying the code ourselves locally?

Resolved: Need to compile contracts before running tests to allow build artifacts to be created.
