### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pegahcarter** [best-practicers/reviews#63]

**Comment by andytudhope** [comment]
Hello! I have added v0.1 of the Learning Curve Spec in this PR: https://github.com/kernel-community/kernel-v2/pull/105/files

You can view the spec here: https://kernel.community/en/fork-me/learning-curve/

One note at this stage is that @kjr217 and I have changed slightly the `createCourse` functionality to ensure course creators can set their own address to receive yield, rather than returning it all the the `kernelTreasury`. This is reflected in the spec, but not the current contracts, though they will be updated soon (TM).
